In [1]:
import pandas as pd
import numpy as np

In [3]:
whisky = pd.read_csv('whiskies.txt')

In [4]:
whisky

,RowID,Distillery,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral,Postcode,Latitude,Longitude
0,1,Aberfeldy,2,2,2,0,0,2,1,2,2,2,2,2,\tPH15 2EB,286580,749680
1,2,Aberlour,3,3,1,0,0,4,3,2,2,3,3,2,\tAB38 9PJ,326340,842570
2,3,AnCnoc,1,3,2,0,0,2,0,0,2,2,3,2,\tAB5 5LI,352960,839320
3,4,Ardbeg,4,1,4,4,0,0,2,0,1,2,1,0,\tPA42 7EB,141560,646220
4,5,Ardmore,2,2,2,0,0,1,1,1,2,3,1,1,\tAB54 4NH,355350,829140
5,6,ArranIsleOf,2,3,1,1,0,1,1,1,0,1,1,2,KA27 8HJ,194050,649950
6,7,Auchentoshan,0,2,0,0,0,1,1,0,2,2,3,3,G81 4SJ,247670,672610
7,8,Auchroisk,2,3,1,0,0,2,1,2,2,2,2,1,\tAB55 3XS,340754,848623
8,9,Aultmore,2,2,1,0,0,1,0,0,2,2,2,2,\tAB55 3QY,340754,848623
9,10,Balblair,2,3,2,1,0,0,2,0,2,1,2,1,\tIV19 1LB,270820,885770
10,11,Balmenach,4,3,2,0,0,2,1,3,3,0,1,2,\tPH26 3PF,307750,827170
11,12,Belvenie,3,2,1,0,0,3,2,1,0,2,2,2,\tAB55 4DH,332680,840840
12,13,BenNevis,4,2,2,0,0,2,2,0,2,2,2,2,\tPH33 6TJ,212600,775710
13,14,Benriach,2,2,1,0,0,2,2,0,0,2,3,2,\tIV30 8SJ,323450,858380
14,15,Benrinnes,3,2,2,0,0,3,1,1,2,3,2,2,\tAB38 9NN,325800,839920
15,16,Benromach,2,2,2,0,0,2,2,1,2,2,2,2,\tIV36 3EB,303330,859350
16,17,Bladnoch,1,2,1,0,0,0,1,1,0,2,2,3,\tDG8 9AB,242260,554260
17,18,BlairAthol,2,2,2,0,0,1,2,2,2,2,2,2,\tPH16 5LY,294860,757580
18,19,Bowmore,2,2,3,1,0,2,2,1,1,1,1,2,\tPA43 7GS,131330,659720
19,20,Bruichladdich,1,1,2,2,0,2,2,1,2,2,2,2,PA49 7UN,126680,661400
20,21,Bunnahabhain,1,2,1,1,0,1,1,1,1,2,2,3,PA46 7RR,142210,673170
21,22,Caol Ila,3,1,4,2,1,0,2,0,2,1,1,1,\tPA46 7RL,142920,670040
22,23,Cardhu,1,3,1,0,0,1,1,0,2,2,2,2,\tAB38 7RY,318790,843090
23,24,Clynelish,3,2,3,3,1,0,2,0,1,1,2,0,\tKW9 6LB,290250,904230
24,25,Craigallechie,2,2,2,0,1,2,2,1,2,2,1,4,AB38 9ST,328920,844920
25,26,Craigganmore,2,3,2,1,0,0,1,0,2,2,2,2,AB37 9AB,316600,836370
26,27,Dailuaine,4,2,2,0,0,1,2,2,2,2,2,1,\tAB38 7RE,323520,841010
27,28,Dalmore,3,2,2,1,0,1,2,2,1,2,3,1,\tIV17 0UT,266610,868730
28,29,Dalwhinnie,2,2,2,0,0,2,1,0,1,2,2,2,\tPH19 1AB,263670,785270
29,30,Deanston,2,2,1,0,0,2,1,1,1,3,2,1,FK16 6AG,271570,701570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,57,Knochando,2,3,1,0,0,2,2,1,2,1,2,2,AB38 7RT,319470,841570
57,58,Lagavulin,4,1,4,4,1,0,1,2,1,1,1,0,PA42 7DZ,140430,645730
58,59,Laphroig,4,2,4,4,1,0,0,1,1,1,0,0,PA42 7DU,138680,645160
59,60,Linkwood,2,3,1,0,0,1,1,2,0,1,3,2,IV30 3RD,322640,861040
60,61,Loch Lomond,1,1,1,1,0,1,1,0,1,2,1,2,G83 0TL,239370,680920
61,62,Longmorn,3,2,1,0,0,1,1,1,3,3,2,3,IV30 3SJ,322640,861040
62,63,Macallan,4,3,1,0,0,2,1,4,2,2,3,1,AB38 9RX,327710,844480
63,64,Mannochmore,2,1,1,0,0,1,1,1,2,1,2,2,IV30 3SS,322640,861040
64,65,Miltonduff,2,4,1,0,0,1,0,0,2,1,1,2,IV30 3TQ,322640,861040
65,66,Mortlach,3,2,2,0,0,2,3,3,2,1,2,2,AB55 4AQ,332950,839850
66,67,Oban,2,2,2,2,0,0,2,0,2,2,2,0,PA34 5NH,185940,730190
67,68,OldFettercairn,1,2,2,0,1,2,2,1,2,3,1,1,AB30 1YE,370860,772900
68,69,OldPulteney,2,1,2,2,1,0,1,1,2,2,2,2,KW1 5BA,336730,950130
69,70,RoyalBrackla,2,3,2,1,1,1,2,1,0,2,3,2,IV12 5QY,286040,851320
70,71,RoyalLochnagar,3,2,2,0,0,2,2,2,2,2,3,1,AB35 5TB,326140,794370
71,72,Scapa,2,2,1,1,0,2,1,1,2,2,2,2,KW15 1SE,342850,1008930
72,73,Speyburn,2,4,1,0,0,2,1,0,0,2,1,2,AB38 7AG,326930,851430
73,74,Speyside,2,2,1,0,0,1,0,1,2,2,2,2,PH21 1NS,278740,800600
74,75,Springbank,2,2,2,2,0,2,2,1,2,1,0,1,PA28 6EJ,172280,620910
75,76,Strathisla,2,2,1,0,0,2,2,2,3,3,3,2,AB55 3BS,340754,848623
76,77,Strathmill,2,3,1,0,0,0,2,0,2,1,3,2,AB55 5DQ,342650,850500
77,78,Talisker,4,2,3,3,0,1,3,0,1,2,2,0,IV47 8SR,137950,831770
78,79,Tamdhu,1,2,1,0,0,2,0,1,1,2,2,2,AB38 7RP,319210,841760
79,80,Tamnavulin,1,3,2,0,0,0,2,0,2,1,2,3,AB37 9JA,321180,826110
80,81,Teaninich,2,2,2,1,0,0,2,0,0,0,2,2,IV17 0XB,265360,869120
81,82,Tobermory,1,1,1,0,0,1,0,0,1,2,2,2,PA75 6NR,150450,755070
82,83,Tomatin,2,3,2,0,0,2,2,1,1,2,0,1,IV13 7YT,279120,829630
83,84,Tomintoul,0,3,1,0,0,2,2,1,1,2,1,2,AB37 9AQ,315100,825560
84,85,Tormore,2,2,1,0,0,1,0,1,2,1,0,0,PH26 3LR,315180,834960
85,86,Tullibardine,2,3,0,0,1,0,2,1,1,2,2,1,PH4 1QG,289690,708850

In [5]:
whisky['Region'] = pd.read_csv('regions.txt')

In [6]:
whisky

,RowID,Distillery,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral,Postcode,Latitude,Longitude,Region
0,1,Aberfeldy,2,2,2,0,0,2,1,2,2,2,2,2,\tPH15 2EB,286580,749680,Highlands
1,2,Aberlour,3,3,1,0,0,4,3,2,2,3,3,2,\tAB38 9PJ,326340,842570,Speyside
2,3,AnCnoc,1,3,2,0,0,2,0,0,2,2,3,2,\tAB5 5LI,352960,839320,Highlands
3,4,Ardbeg,4,1,4,4,0,0,2,0,1,2,1,0,\tPA42 7EB,141560,646220,Islay
4,5,Ardmore,2,2,2,0,0,1,1,1,2,3,1,1,\tAB54 4NH,355350,829140,Highlands
5,6,ArranIsleOf,2,3,1,1,0,1,1,1,0,1,1,2,KA27 8HJ,194050,649950,Islands
6,7,Auchentoshan,0,2,0,0,0,1,1,0,2,2,3,3,G81 4SJ,247670,672610,Lowlands
7,8,Auchroisk,2,3,1,0,0,2,1,2,2,2,2,1,\tAB55 3XS,340754,848623,Speyside
8,9,Aultmore,2,2,1,0,0,1,0,0,2,2,2,2,\tAB55 3QY,340754,848623,Speyside
9,10,Balblair,2,3,2,1,0,0,2,0,2,1,2,1,\tIV19 1LB,270820,885770,Highlands
10,11,Balmenach,4,3,2,0,0,2,1,3,3,0,1,2,\tPH26 3PF,307750,827170,Speyside
11,12,Belvenie,3,2,1,0,0,3,2,1,0,2,2,2,\tAB55 4DH,332680,840840,Speyside
12,13,BenNevis,4,2,2,0,0,2,2,0,2,2,2,2,\tPH33 6TJ,212600,775710,Highlands
13,14,Benriach,2,2,1,0,0,2,2,0,0,2,3,2,\tIV30 8SJ,323450,858380,Speyside
14,15,Benrinnes,3,2,2,0,0,3,1,1,2,3,2,2,\tAB38 9NN,325800,839920,Speyside
15,16,Benromach,2,2,2,0,0,2,2,1,2,2,2,2,\tIV36 3EB,303330,859350,Speyside
16,17,Bladnoch,1,2,1,0,0,0,1,1,0,2,2,3,\tDG8 9AB,242260,554260,Lowlands
17,18,BlairAthol,2,2,2,0,0,1,2,2,2,2,2,2,\tPH16 5LY,294860,757580,Highlands
18,19,Bowmore,2,2,3,1,0,2,2,1,1,1,1,2,\tPA43 7GS,131330,659720,Islay
19,20,Bruichladdich,1,1,2,2,0,2,2,1,2,2,2,2,PA49 7UN,126680,661400,Islay
20,21,Bunnahabhain,1,2,1,1,0,1,1,1,1,2,2,3,PA46 7RR,142210,673170,Islay
21,22,Caol Ila,3,1,4,2,1,0,2,0,2,1,1,1,\tPA46 7RL,142920,670040,Islay
22,23,Cardhu,1,3,1,0,0,1,1,0,2,2,2,2,\tAB38 7RY,318790,843090,Speyside
23,24,Clynelish,3,2,3,3,1,0,2,0,1,1,2,0,\tKW9 6LB,290250,904230,Highlands
24,25,Craigallechie,2,2,2,0,1,2,2,1,2,2,1,4,AB38 9ST,328920,844920,Speyside
25,26,Craigganmore,2,3,2,1,0,0,1,0,2,2,2,2,AB37 9AB,316600,836370,Speyside
26,27,Dailuaine,4,2,2,0,0,1,2,2,2,2,2,1,\tAB38 7RE,323520,841010,Speyside
27,28,Dalmore,3,2,2,1,0,1,2,2,1,2,3,1,\tIV17 0UT,266610,868730,Highlands
28,29,Dalwhinnie,2,2,2,0,0,2,1,0,1,2,2,2,\tPH19 1AB,263670,785270,Highlands
29,30,Deanston,2,2,1,0,0,2,1,1,1,3,2,1,FK16 6AG,271570,701570,Highlands
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,57,Knochando,2,3,1,0,0,2,2,1,2,1,2,2,AB38 7RT,319470,841570,Speyside
57,58,Lagavulin,4,1,4,4,1,0,1,2,1,1,1,0,PA42 7DZ,140430,645730,Islay
58,59,Laphroig,4,2,4,4,1,0,0,1,1,1,0,0,PA42 7DU,138680,645160,Islay
59,60,Linkwood,2,3,1,0,0,1,1,2,0,1,3,2,IV30 3RD,322640,861040,Speyside
60,61,Loch Lomond,1,1,1,1,0,1,1,0,1,2,1,2,G83 0TL,239370,680920,Highlands
61,62,Longmorn,3,2,1,0,0,1,1,1,3,3,2,3,IV30 3SJ,322640,861040,Speyside
62,63,Macallan,4,3,1,0,0,2,1,4,2,2,3,1,AB38 9RX,327710,844480,Speyside
63,64,Mannochmore,2,1,1,0,0,1,1,1,2,1,2,2,IV30 3SS,322640,861040,Speyside
64,65,Miltonduff,2,4,1,0,0,1,0,0,2,1,1,2,IV30 3TQ,322640,861040,Speyside
65,66,Mortlach,3,2,2,0,0,2,3,3,2,1,2,2,AB55 4AQ,332950,839850,Speyside
66,67,Oban,2,2,2,2,0,0,2,0,2,2,2,0,PA34 5NH,185940,730190,Highlands
67,68,OldFettercairn,1,2,2,0,1,2,2,1,2,3,1,1,AB30 1YE,370860,772900,Highlands
68,69,OldPulteney,2,1,2,2,1,0,1,1,2,2,2,2,KW1 5BA,336730,950130,Highlands
69,70,RoyalBrackla,2,3,2,1,1,1,2,1,0,2,3,2,IV12 5QY,286040,851320,Speyside
70,71,RoyalLochnagar,3,2,2,0,0,2,2,2,2,2,3,1,AB35 5TB,326140,794370,Highlands
71,72,Scapa,2,2,1,1,0,2,1,1,2,2,2,2,KW15 1SE,342850,1008930,Islands
72,73,Speyburn,2,4,1,0,0,2,1,0,0,2,1,2,AB38 7AG,326930,851430,Speyside
73,74,Speyside,2,2,1,0,0,1,0,1,2,2,2,2,PH21 1NS,278740,800600,Speyside
74,75,Springbank,2,2,2,2,0,2,2,1,2,1,0,1,PA28 6EJ,172280,620910,Campbelltown
75,76,Strathisla,2,2,1,0,0,2,2,2,3,3,3,2,AB55 3BS,340754,848623,Speyside
76,77,Strathmill,2,3,1,0,0,0,2,0,2,1,3,2,AB55 5DQ,342650,850500,Speyside
77,78,Talisker,4,2,3,3,0,1,3,0,1,2,2,0,IV47 8SR,137950,831770,Islands
78,79,Tamdhu,1,2,1,0,0,2,0,1,1,2,2,2,AB38 7RP,319210,841760,Speyside
79,80,Tamnavulin,1,3,2,0,0,0,2,0,2,1,2,3,AB37 9JA,321180,826110,Speyside
80,81,Teaninich,2,2,2,1,0,0,2,0,0,0,2,2,IV17 0XB,265360,869120,Highlands
81,82,Tobermory,1,1,1,0,0,1,0,0,1,2,2,2,PA75 6NR,150450,755070,Islands
82,83,Tomatin,2,3,2,0,0,2,2,1,1,2,0,1,IV13 7YT,279120,829630,Highlands
83,84,Tomintoul,0,3,1,0,0,2,2,1,1,2,1,2,AB37 9AQ,315100,825560,Speyside
84,85,Tormore,2,2,1,0,0,1,0,1,2,1,0,0,PH26 3LR,315180,834960,Speyside
85,86,Tullibardine,2,3,0,0,1,0,2,1,1,2,2,1,PH4 1QG,289690,708850,Highlands

In [9]:
whisky.head()

,RowID,Distillery,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral,Postcode,Latitude,Longitude,Region
0,1,Aberfeldy,2,2,2,0,0,2,1,2,2,2,2,2,\tPH15 2EB,286580,749680,Highlands
1,2,Aberlour,3,3,1,0,0,4,3,2,2,3,3,2,\tAB38 9PJ,326340,842570,Speyside
2,3,AnCnoc,1,3,2,0,0,2,0,0,2,2,3,2,\tAB5 5LI,352960,839320,Highlands
3,4,Ardbeg,4,1,4,4,0,0,2,0,1,2,1,0,\tPA42 7EB,141560,646220,Islay
4,5,Ardmore,2,2,2,0,0,1,1,1,2,3,1,1,\tAB54 4NH,355350,829140,Highlands

In [10]:
whisky.tail()

,RowID,Distillery,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral,Postcode,Latitude,Longitude,Region
81,82,Tobermory,1,1,1,0,0,1,0,0,1,2,2,2,PA75 6NR,150450,755070,Islands
82,83,Tomatin,2,3,2,0,0,2,2,1,1,2,0,1,IV13 7YT,279120,829630,Highlands
83,84,Tomintoul,0,3,1,0,0,2,2,1,1,2,1,2,AB37 9AQ,315100,825560,Speyside
84,85,Tormore,2,2,1,0,0,1,0,1,2,1,0,0,PH26 3LR,315180,834960,Speyside
85,86,Tullibardine,2,3,0,0,1,0,2,1,1,2,2,1,PH4 1QG,289690,708850,Highlands

In [11]:
whisky.iloc[0:10]

,RowID,Distillery,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral,Postcode,Latitude,Longitude,Region
0,1,Aberfeldy,2,2,2,0,0,2,1,2,2,2,2,2,\tPH15 2EB,286580,749680,Highlands
1,2,Aberlour,3,3,1,0,0,4,3,2,2,3,3,2,\tAB38 9PJ,326340,842570,Speyside
2,3,AnCnoc,1,3,2,0,0,2,0,0,2,2,3,2,\tAB5 5LI,352960,839320,Highlands
3,4,Ardbeg,4,1,4,4,0,0,2,0,1,2,1,0,\tPA42 7EB,141560,646220,Islay
4,5,Ardmore,2,2,2,0,0,1,1,1,2,3,1,1,\tAB54 4NH,355350,829140,Highlands
5,6,ArranIsleOf,2,3,1,1,0,1,1,1,0,1,1,2,KA27 8HJ,194050,649950,Islands
6,7,Auchentoshan,0,2,0,0,0,1,1,0,2,2,3,3,G81 4SJ,247670,672610,Lowlands
7,8,Auchroisk,2,3,1,0,0,2,1,2,2,2,2,1,\tAB55 3XS,340754,848623,Speyside
8,9,Aultmore,2,2,1,0,0,1,0,0,2,2,2,2,\tAB55 3QY,340754,848623,Speyside
9,10,Balblair,2,3,2,1,0,0,2,0,2,1,2,1,\tIV19 1LB,270820,885770,Highlands

In [15]:
whisky.iloc[5:10, 0:5] #row, columns

   RowID    Distillery  Body  Sweetness  Smoky
5      6   ArranIsleOf     2          3      1
6      7  Auchentoshan     0          2      0
7      8     Auchroisk     2          3      1
8      9      Aultmore     2          2      1
9     10      Balblair     2          3      2

In [19]:
whisky.columns

Index(['RowID', 'Distillery', 'Body', 'Sweetness', 'Smoky', 'Medicinal',
       'Tobacco', 'Honey', 'Spicy', 'Winey', 'Nutty', 'Malty', 'Fruity',
       'Floral', 'Postcode', ' Latitude', ' Longitude', 'Region'],
      dtype='object')

In [21]:
flavors = whisky.iloc[:, 2:14]

In [22]:
flavors

,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral
0,2,2,2,0,0,2,1,2,2,2,2,2
1,3,3,1,0,0,4,3,2,2,3,3,2
2,1,3,2,0,0,2,0,0,2,2,3,2
3,4,1,4,4,0,0,2,0,1,2,1,0
4,2,2,2,0,0,1,1,1,2,3,1,1
5,2,3,1,1,0,1,1,1,0,1,1,2
6,0,2,0,0,0,1,1,0,2,2,3,3
7,2,3,1,0,0,2,1,2,2,2,2,1
8,2,2,1,0,0,1,0,0,2,2,2,2
9,2,3,2,1,0,0,2,0,2,1,2,1
10,4,3,2,0,0,2,1,3,3,0,1,2
11,3,2,1,0,0,3,2,1,0,2,2,2
12,4,2,2,0,0,2,2,0,2,2,2,2
13,2,2,1,0,0,2,2,0,0,2,3,2
14,3,2,2,0,0,3,1,1,2,3,2,2
15,2,2,2,0,0,2,2,1,2,2,2,2
16,1,2,1,0,0,0,1,1,0,2,2,3
17,2,2,2,0,0,1,2,2,2,2,2,2
18,2,2,3,1,0,2,2,1,1,1,1,2
19,1,1,2,2,0,2,2,1,2,2,2,2
20,1,2,1,1,0,1,1,1,1,2,2,3
21,3,1,4,2,1,0,2,0,2,1,1,1
22,1,3,1,0,0,1,1,0,2,2,2,2
23,3,2,3,3,1,0,2,0,1,1,2,0
24,2,2,2,0,1,2,2,1,2,2,1,4
25,2,3,2,1,0,0,1,0,2,2,2,2
26,4,2,2,0,0,1,2,2,2,2,2,1
27,3,2,2,1,0,1,2,2,1,2,3,1
28,2,2,2,0,0,2,1,0,1,2,2,2
29,2,2,1,0,0,2,1,1,1,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
56,2,3,1,0,0,2,2,1,2,1,2,2
57,4,1,4,4,1,0,1,2,1,1,1,0
58,4,2,4,4,1,0,0,1,1,1,0,0
59,2,3,1,0,0,1,1,2,0,1,3,2
60,1,1,1,1,0,1,1,0,1,2,1,2
61,3,2,1,0,0,1,1,1,3,3,2,3
62,4,3,1,0,0,2,1,4,2,2,3,1
63,2,1,1,0,0,1,1,1,2,1,2,2
64,2,4,1,0,0,1,0,0,2,1,1,2
65,3,2,2,0,0,2,3,3,2,1,2,2
66,2,2,2,2,0,0,2,0,2,2,2,0
67,1,2,2,0,1,2,2,1,2,3,1,1
68,2,1,2,2,1,0,1,1,2,2,2,2
69,2,3,2,1,1,1,2,1,0,2,3,2
70,3,2,2,0,0,2,2,2,2,2,3,1
71,2,2,1,1,0,2,1,1,2,2,2,2
72,2,4,1,0,0,2,1,0,0,2,1,2
73,2,2,1,0,0,1,0,1,2,2,2,2
74,2,2,2,2,0,2,2,1,2,1,0,1
75,2,2,1,0,0,2,2,2,3,3,3,2
76,2,3,1,0,0,0,2,0,2,1,3,2
77,4,2,3,3,0,1,3,0,1,2,2,0
78,1,2,1,0,0,2,0,1,1,2,2,2
79,1,3,2,0,0,0,2,0,2,1,2,3
80,2,2,2,1,0,0,2,0,0,0,2,2
81,1,1,1,0,0,1,0,0,1,2,2,2
82,2,3,2,0,0,2,2,1,1,2,0,1
83,0,3,1,0,0,2,2,1,1,2,1,2
84,2,2,1,0,0,1,0,1,2,1,0,0
85,2,3,0,0,1,0,2,1,1,2,2,1

#### Loading and Inspecting Data: Question 1

What command reads in csv files in pandas ?

- ```pd.csv_read```
- ```pd.csv```
- ```pd.read(type="csv")```
- **```pd.read_csv```**